import AiPromptStudioTool from '@/components/AiPromptStudioTool';
import SeoSection from '@/components/SeoSection';
import IndexOnly from '@/components/SeoSection/IndexOnly';
import AdSlot from '@/components/AdSlot';
import styles from '../tool-page.module.css';
import DisqusComments from '@/components/DisqusComments';

export const metadata = {
  title: 'AI Prompt Studio — Free Prompt Improver, Analyzer & Templates | webdevpuneet.com',
  description: 'Free AI prompt engineering tool — score prompts across 8 dimensions, detect anti-patterns, and optimize for ChatGPT, Claude, and Gemini. Browser-based.',
  authors: [{ name: 'Puneet Sharma', url: 'https://www.webdevpuneet.com/' }],
  robots: { index: true, follow: true },
  alternates: { canonical: 'https://webdevpuneet.com/ai-prompt-studio/' },
  icons: { icon: '/icons/ai-prompt-studio.svg', shortcut: '/icons/ai-prompt-studio.svg' },
  openGraph: { type: 'website', url: 'https://webdevpuneet.com/ai-prompt-studio/', siteName: 'webdevpuneet.com', title: 'AI Prompt Studio — Prompt Analyzer, Optimizer & Template Library', description: 'Score prompts across 8 dimensions, fix anti-patterns, optimize for ChatGPT/Claude/Gemini, use 23 expert templates, and save a personal prompt library. Free, no sign-up.', images: [{ url: 'https://webdevpuneet.com/images/ai-prompt-studio.png', width: 1200, height: 630, alt: 'AI Prompt Studio' }], locale: 'en_US' },
  twitter: { card: 'summary_large_image', site: '@webdevpuneet', title: 'AI Prompt Studio — Write Better Prompts for ChatGPT, Claude & Gemini', description: 'Score, improve, and optimize your AI prompts. 8-dimension quality analyzer, 23 expert templates, model-specific optimizer. Free.', images: ['https://webdevpuneet.com/images/ai-prompt-studio.png'] },
};

const faqSchema = {
  '@context': 'https://schema.org', '@type': 'FAQPage',
  mainEntity: [
    { '@type': 'Question', name: 'What is prompt engineering and why does it matter?', acceptedAnswer: { '@type': 'Answer', text: 'Prompt engineering is the practice of structuring your instructions to an AI model so that it produces more accurate, useful, and consistent outputs. A poorly written prompt like "summarize this" can get a generic 3-sentence answer, while a well-engineered prompt that specifies role, format, length, audience, and constraints might get exactly the executive summary you need formatted as a bulleted list for a non-technical audience. The difference between a weak and strong prompt is often the difference between needing 10 back-and-forth messages and getting the right answer on the first try. Good prompt engineering is now a fundamental skill for developers, writers, analysts, and anyone who works with AI tools regularly.' } },
    { '@type': 'Question', name: 'How does the prompt quality score work?', acceptedAnswer: { '@type': 'Answer', text: 'The scorer analyzes your prompt across 8 dimensions: Role/Persona (does it tell the model who it should act as?), Task Clarity (does it use a clear action verb?), Output Format (does it specify how to structure the response?), Context (does it provide relevant background?), Constraints (does it set boundaries on what to include or exclude?), Examples (does it show the model what good output looks like?), Audience (does it specify who the response is for?), and Tone (does it define the voice or register?). Each dimension is scored 0–10 using keyword and pattern detection. The overall score is the average across all 8 dimensions. A score of 7+ is considered a strong prompt, 4–6 is moderate, and below 4 needs significant improvement.' } },
    { '@type': 'Question', name: 'What are anti-patterns in AI prompts?', acceptedAnswer: { '@type': 'Answer', text: 'Anti-patterns are common mistakes that reduce prompt effectiveness. The detector checks for six main issues: prompts that are too short (under 60 characters lack enough context for a good response), vague language (words like "good", "nice", "something" give the model nothing specific to work with), filler starts (beginning with "Please", "Can you", "Could you" wastes the leading context window on politeness instead of instruction), contradictory instructions (telling the model to be "concise but comprehensive" or "brief but detailed" creates ambiguity), missing action verbs (the prompt has no clear directive like Write, Analyze, List, or Compare), and missing output format (the model cannot format the response optimally without knowing whether you want a list, JSON, paragraphs, or a table).' } },
    { '@type': 'Question', name: 'How is the Claude-optimized prompt different from the ChatGPT or Gemini version?', acceptedAnswer: { '@type': 'Answer', text: 'Each model has different architectural strengths that respond to different prompt structures. Claude is trained to respect XML tags as semantic containers, so the optimizer wraps your instructions in <instructions>, <role>, and <output_format> tags that give Claude explicit structural boundaries. ChatGPT (GPT-4 and later) responds well to explicit persona framing at the start of the system prompt and numbered step-by-step instructions that define the approach before answering. Gemini benefits from chain-of-thought priming ("Think step by step before answering") and explicit output format declarations with headers, which align with its tendency to produce well-organized multi-section responses. In practice, these differences matter most for complex tasks — for simple queries all three models handle any reasonable prompt well.' } },
    { '@type': 'Question', name: 'How do I write a good role or persona for my prompt?', acceptedAnswer: { '@type': 'Answer', text: 'A role tells the model to draw on a specific domain of knowledge and adopt a particular communication style. "You are a senior software engineer" activates coding knowledge, best practices, and a technical vocabulary. "You are a conversion copywriter with 15 years of experience" primes the model for persuasive, benefit-focused language. The key is to be specific about expertise level and domain — "You are an expert" is weaker than "You are a senior DevOps engineer who specializes in Kubernetes and CI/CD pipelines". You can also add context about the role\'s perspective: "You are a skeptical code reviewer whose job is to find problems, not to be encouraging." This shapes not just what the model knows but how it frames its answer.' } },
    { '@type': 'Question', name: 'What is the difference between a constraint and a context in a prompt?', acceptedAnswer: { '@type': 'Answer', text: 'Context is background information that helps the model understand the situation — who you are, what the goal is, what the audience expects, or what problem you are trying to solve. Constraints are rules that define the boundaries of the output — what to include, what to exclude, maximum length, format requirements, or what to avoid. For example: "I am preparing a report for non-technical stakeholders" is context. "Do not use technical jargon, keep each section under 100 words, and avoid recommending any specific vendor" are constraints. Strong prompts usually have both — context shapes the model\'s understanding of the task, constraints shape the acceptable output.' } },
    { '@type': 'Question', name: 'Can I save my prompts and access them later?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Click the Save button above the editor to store the current prompt in your personal library with a custom title. Saved prompts persist in your browser\'s localStorage and remain available across sessions — they are not deleted when you close the tab. The library shows each saved prompt with its quality score so you can track which versions performed best. You can load, copy, or delete any saved prompt at any time. Since localStorage is browser-specific, your library is private to your device and is not synced to other browsers or devices. Use the Share button to generate a shareable URL that encodes the prompt — anyone with the link can open it in the tool.' } },
    { '@type': 'Question', name: 'How does prompt sharing work?', acceptedAnswer: { '@type': 'Answer', text: 'Clicking Share copies a URL to your clipboard that encodes your current prompt as a URL parameter using Base64 encoding. When someone opens that URL, the tool automatically loads the prompt into the editor so they can use, edit, or analyze it immediately. This works entirely in the browser — no account, no server, no data is stored anywhere. The URL contains the full prompt encoded in the link itself, which means very long prompts will produce long URLs. Share links work on any modern browser and do not expire. This is useful for sharing prompt templates with teammates, posting example prompts in documentation, or archiving a prompt in a bookmark.' } },
    { '@type': 'Question', name: 'What is the best way to specify output format in a prompt?', acceptedAnswer: { '@type': 'Answer', text: 'Be explicit and specific rather than implicit and general. Instead of hoping the model will use a list, write "Format your response as a numbered list where each item has: [Severity: Critical/High/Medium/Low] → Problem description → Suggested fix." If you want JSON, provide the exact schema: "Respond with a JSON object with keys: title (string), summary (string, max 2 sentences), tags (array of strings)." If you want markdown, say "Use markdown with H2 headings for each section." If you want a specific length, say "Under 200 words" or "Exactly 5 bullet points." The more precisely you describe the structure, the more consistently the model reproduces it across multiple prompts on the same task.' } },
    { '@type': 'Question', name: 'How do I use examples (few-shot prompting) effectively?', acceptedAnswer: { '@type': 'Answer', text: 'Few-shot prompting means including one or more examples of the input-output pair you want the model to replicate. It is one of the most powerful techniques for improving consistency, especially for formatting tasks, classification, or custom writing styles. Structure your examples clearly: "Input: [example input] → Output: [example output]". Use 1–3 examples — more than that often yields diminishing returns and wastes context tokens. Make your examples representative of the real inputs you will use, not edge cases. If you want to override the model\'s default style — tone, brevity, technical level — a single well-chosen example often works better than 3 paragraphs of style instructions. The AI Prompt Studio scorer rewards prompts that include examples with up to 10 points in the Examples dimension.' } },
    { '@type': 'Question', name: 'What is chain-of-thought prompting and when should I use it?', acceptedAnswer: { '@type': 'Answer', text: 'Chain-of-thought (CoT) prompting instructs the model to reason through a problem step by step before giving a final answer. For simple factual or formatting tasks it adds unnecessary length — just ask for the answer directly. But for multi-step reasoning tasks — math problems, logical deductions, code debugging, legal analysis, strategic decisions — CoT significantly improves accuracy because the model\'s intermediate reasoning steps catch errors that a direct-answer prompt would skip over. Add it by including "Think step by step before answering" or "Show your reasoning before stating the conclusion." The Gemini optimizer in AI Prompt Studio automatically adds this priming because Gemini\'s architecture benefits from it on complex tasks. For Claude, you can achieve the same effect with an <thinking> block in the prompt.' } },
    { '@type': 'Question', name: 'Why does my prompt score high but still get a bad response from the AI?', acceptedAnswer: { '@type': 'Answer', text: 'The quality score measures the structural completeness of your prompt — whether it has role, task, format, context, constraints, examples, audience, and tone. It does not evaluate whether your content is accurate, whether your constraints are logically consistent, or whether your use case is within the model\'s capability. A prompt can score 8/10 structurally and still produce a poor result if the task itself is inherently difficult, the model lacks domain knowledge, the context you provided is incorrect, or your constraints conflict in ways the scorer does not detect. Use the score as a signal that your prompt is well-structured, then evaluate the actual output quality by testing with the AI. If output quality is consistently poor despite a high score, try adding more specific examples, breaking the task into smaller sub-tasks, or switching models using the Optimize tab.' } },
    { '@type': 'Question', name: 'How do I write prompts for coding tasks specifically?', acceptedAnswer: { '@type': 'Answer', text: 'Effective coding prompts follow a consistent structure: (1) Role — "You are a senior [language] developer." (2) Task — use a precise verb: Implement, Debug, Refactor, Review, Explain, Write tests for. (3) Language and framework — never leave these implicit: "In Python 3.11 using FastAPI." (4) Input/output contract — describe exactly what the function should take and return. (5) Constraints — "Do not use external libraries beyond the standard library", "Preserve the existing function signature", "Handle empty input gracefully." (6) Format — "Return only the code without explanation", or "Include inline comments for non-obvious logic", or "Follow PEP 8 style." (7) Context — paste the existing code or error message. The Coding templates in AI Prompt Studio are pre-structured with all these elements — use one as a starting point rather than building from scratch.' } },
    { '@type': 'Question', name: 'What is the difference between a system prompt and a user prompt?', acceptedAnswer: { '@type': 'Answer', text: 'In models that support it (ChatGPT API, Claude API, Gemini API), the system prompt is a persistent instruction set that defines the model\'s behavior for the entire conversation — the role, rules, output style, and scope. The user prompt is the specific message or task for each individual turn. In API usage, system prompts are sent in the "system" field; in chat interfaces like ChatGPT, you set them in the "Custom instructions" section. For one-off tasks in a chat interface, combining both in a single user message works fine — put the role and rules at the top, then the specific task. The templates in AI Prompt Studio are designed for this single-message pattern, which is the most common use case for browser-based tools and chat interfaces.' } },
    { '@type': 'Question', name: 'How long should my prompt be?', acceptedAnswer: { '@type': 'Answer', text: 'There is no single correct length — the right length is whatever it takes to unambiguously define the task. Very short prompts (under 60 characters) almost always underspecify the task. Very long prompts (over 2,000 words) risk burying the key instruction in surrounding context, and some models give less weight to instructions that appear late in a very long prompt. A practical target for most tasks is 100–400 words: enough to cover role, task, format, context, and constraints without padding. If your task genuinely requires a long brief — a detailed persona, a multi-page document style guide, or complex business rules — longer is fine. What to avoid: long prompts that are long because they repeat the same instruction in three different ways or add unnecessary politeness. Every sentence should add information the model needs.' } },
    { '@type': 'Question', name: 'Does adding "please" or "thank you" to a prompt affect the response quality?', acceptedAnswer: { '@type': 'Answer', text: 'Politeness words like "Please", "Can you", "Could you kindly", and "Thank you" have no positive effect on response quality and are a detectable anti-pattern in AI Prompt Studio. They consume context tokens and position your actual instruction further from the start of the prompt, which can reduce how much weight the model gives it. More importantly, starting with "Please write me a summary" signals a conversational framing that tends to produce more casual, less structured output compared to leading with a direct imperative: "Summarize the following in 3 bullet points, each under 20 words, focusing on the business impact." The model does not have feelings to hurt. Lead with the action.' } },
    { '@type': 'Question', name: 'Can I use AI Prompt Studio for image generation prompts (Midjourney, DALL-E, Stable Diffusion)?', acceptedAnswer: { '@type': 'Answer', text: 'The quality scorer and templates are designed for text-based language models (ChatGPT, Claude, Gemini, Llama, etc.) and the scoring dimensions — Role, Task, Format, Context, Constraints, Examples, Audience, Tone — are meaningful for that context. Image generation prompts follow a different grammar: subject, style, lighting, camera settings, mood, artist references, aspect ratio. The scorer will still run on image prompts and flag structural issues, but a score of 4/10 on a Midjourney prompt does not mean the image output will be poor. You can still use the editor to draft, refine, and save image prompts in your library, and the Share and Copy buttons work for any text content. The Templates and Optimize tabs are best used for language model tasks.' } },
    { '@type': 'Question', name: 'How do I improve a prompt that produces inconsistent results across multiple runs?', acceptedAnswer: { '@type': 'Answer', text: 'Inconsistency usually comes from underspecification — the prompt leaves room for the model to make different choices on each run. Fix it by locking down the ambiguous dimensions. If the length varies, add a word or sentence count: "Respond in exactly 5 bullet points, each 1–2 sentences." If the structure varies, provide a rigid template: "Always use this format: [Header] → [1-paragraph explanation] → [Code example if applicable]." If the tone varies, describe it explicitly: "Use formal, direct language — no casual asides or hedging phrases like \'it is worth noting\'." If specific terminology is inconsistent, define it: "Always use the term \'feature flag\' not \'feature toggle\' or \'flag\'." The more the model can fill in with its own judgment, the more the output will vary. Reduce judgment by making every output element explicit.' } },
    { '@type': 'Question', name: 'Is my data safe? Does the tool send my prompts anywhere?', acceptedAnswer: { '@type': 'Answer', text: 'All analysis runs entirely in your browser using JavaScript — no prompt content is sent to any server at any point. The quality scorer, anti-pattern detector, and model optimizer are all rule-based algorithms running client-side. Your prompts are stored only in your browser\'s localStorage when you explicitly click Save — that data lives on your device and is never transmitted. The Share feature encodes your prompt in the URL itself (Base64) rather than storing it server-side, so sharing is also zero-server. You can safely use this tool with confidential internal documents, proprietary business logic, sensitive API instructions, or any content you would not want to send to a third-party service.' } },
  ],
};

const softwareSchema = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'AI Prompt Studio',
  url: 'https://webdevpuneet.com/ai-prompt-studio/',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'Web',
  browserRequirements: 'Requires JavaScript',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  description: 'Free browser-based AI prompt engineering tool with 8-dimension quality scoring, anti-pattern detection, model-specific optimizer for Claude/ChatGPT/Gemini, 23 expert templates, and local prompt library.',
  featureList: ['8-dimension prompt quality scorer', 'Anti-pattern detector (6 checks)', 'Model optimizer for Claude, ChatGPT, Gemini', '23 expert prompt templates across 7 categories', 'Personal prompt library with localStorage', 'URL-based prompt sharing', 'Word and character counter', '100% browser-based — no data sent to any server'],
  author: { '@type': 'Person', name: 'Puneet Sharma', url: 'https://www.webdevpuneet.com/' },
};

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://webdevpuneet.com' },
    { '@type': 'ListItem', position: 2, name: 'AI Prompt Studio', item: 'https://webdevpuneet.com/ai-prompt-studio/' },
  ],
};

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Use AI Prompt Studio',
  description: 'Free — Score, fix, and optimize AI prompts for ChatGPT, Claude, and Gemini in 8 steps.',
  step: [
    { '@type': 'HowToStep', position: 1, name: 'Write or paste your prompt into the editor', text: 'Type directly in the large editor on the left, or paste an existing prompt you want to improve. The quality score and mini bar chart at the bottom update in real time as you type — you can watch individual dimension bars rise as you add a role, a format, or constraints.' },
    { '@type': 'HowToStep', position: 2, name: 'Read the Analyze tab for the full breakdown', text: 'Click the Analyze tab on the right panel to see the overall score (0–10) and scores for all 8 dimensions: Role, Task, Format, Context, Constraints, Examples, Audience, and Tone. The Issues Found section lists any detected anti-patterns with specific fix recommendations.' },
    { '@type': 'HowToStep', position: 3, name: 'Fix flagged issues one by one', text: 'Work through each issue in the Issues panel. Add a role ("You are a senior engineer"), specify an output format ("Format as a numbered list"), add constraints ("Avoid style suggestions — focus on bugs and security"), and watch the score climb. Aim for 7 or above before using the prompt.' },
    { '@type': 'HowToStep', position: 4, name: 'Load a template if starting from scratch', text: 'Click the Templates tab, pick a category (Coding, Writing, Analysis, Business, SEO, Data), and click "Use Template" on any card. The template loads into the editor and the analyzer scores it immediately. Replace the [placeholder] sections with your specific content.' },
    { '@type': 'HowToStep', position: 5, name: 'Optimize for your target AI model', text: 'Click the Optimize tab and select Claude, ChatGPT, or Gemini. The tool transforms your prompt using model-specific conventions — XML tags for Claude, persona framing and numbered steps for ChatGPT, chain-of-thought priming for Gemini. Copy the result with one click.' },
    { '@type': 'HowToStep', position: 6, name: 'Save prompts you want to reuse', text: 'Click Save above the editor, give the prompt a descriptive title, and confirm. Saved prompts appear in the Library tab with their quality score. They persist in your browser\'s localStorage across sessions — no account needed.' },
    { '@type': 'HowToStep', position: 7, name: 'Search and load from your library', text: 'Open the Library tab, type in the search box to filter by title or content, and click Load to restore any saved prompt into the editor. You can also Copy or Delete from the library.' },
    { '@type': 'HowToStep', position: 8, name: 'Share a prompt with a teammate or bookmark it', text: 'Click Share above the editor to copy a URL that encodes the current prompt. Anyone who opens the link has the prompt pre-loaded in the tool. Use this to share refined templates with teammates, post examples in documentation, or save a prompt as a browser bookmark.' },
  ],
};

const SEO = {
  slug: 'ai-prompt-studio',
  title: 'AI Prompt Studio — Write, Score, and Optimize Prompts for ChatGPT, Claude & Gemini',

  sections: [
    {
      type: '2col',
      left: {
        type: 'text',
        label: 'About this tool',
        heading: 'Stop Getting Generic AI Responses — Diagnose and Fix Your Prompts Before You Send Them',
        text: `You paste a prompt into ChatGPT or Claude, get a mediocre response, iterate five times, and still feel like the model isn't quite getting it. The problem almost always isn't the model — it's the prompt. Vague instructions, missing context, no format specification, and contradictory constraints all send the model in the wrong direction. AI Prompt Studio analyzes your prompt before you submit it, shows you exactly which dimensions are weak, and flags the anti-patterns that silently tank your results.\n\nThe quality scorer evaluates every prompt across 8 structural dimensions: **Role/Persona** (is the model given a clear identity?), **Task Clarity** (is the action explicit?), **Output Format** (does the model know how to structure the response?), **Context** (does the background make the task unambiguous?), **Constraints** (are there clear rules on what to include and exclude?), **Examples** (is there a sample to calibrate against?), **Audience** (does the model know who the response is for?), and **Tone** (is the voice specified?). Each dimension scores 0–10 and the overall score gives you an instant read on prompt quality.\n\nThe anti-pattern detector runs 6 checks against your prompt: prompts that are too short to give the model enough signal, vague words that provide no specificity, filler phrases like "Please can you" that waste the leading context, contradictory instructions that create irresolvable ambiguity, missing action verbs that leave the task undefined, and missing format specifications that force the model to guess the output structure. Each flagged issue includes a specific fix recommendation — not a generic "make it better" suggestion, but the exact element that is missing.\n\nOnce your prompt is solid, the Model Optimizer transforms it for the model you're targeting. Claude's architecture responds best to XML-tagged context blocks (\`<instructions>\`, \`<role>\`, \`<output_format>\`) that give it explicit semantic boundaries. ChatGPT performs better with persona framing at the start and numbered instructional steps. Gemini benefits from chain-of-thought priming and explicit output format headers. One click generates the model-specific version — ready to paste.\n\nThe template library covers 23 expert-crafted starting points across Coding, Writing, Analysis, Creative, Business, SEO, and Data categories. Each template is designed to score 7+ on the quality scorer out of the box — they all specify role, format, and constraints, and leave clearly marked placeholders for your specific content. Build your own library by saving any prompt you've refined — saved prompts persist across sessions in localStorage and each shows its quality score so you can track which versions performed best.`,
      },
      right: {
        type: 'features',
        heading: 'Features',
        items: [
          '8-dimension prompt quality scorer (Role, Task, Format, Context, Constraints, Examples, Audience, Tone) — live score updates as you type',
          'Anti-pattern detector with 6 checks: too-short, vague language, filler starts, contradictions, missing action verb, missing output format — each with a specific fix',
          'Model optimizer for Claude (XML tags), ChatGPT (persona + numbered steps), and Gemini (chain-of-thought + output headers) — one click per model',
          '23 expert-crafted templates across 7 categories: Coding, Writing, Analysis, Creative, Business, SEO, Data — all pre-structured with role, format, and constraints',
          'Personal prompt library with [localStorage](https://fwdtools.com/base64-encoder-decoder) persistence — save with title and score, search, load, copy, or delete',
          'URL-based sharing — Share button encodes your prompt in a link anyone can open in the tool, no account needed',
          'Live word and character counter — useful when working with token-limited models or length-constrained tasks',
          '100% browser-based — no API key required, no data sent to any server; all scoring runs in JavaScript locally',
        ],
      },
    },
    {
      type: 'steps',
      heading: 'How to Use',
      items: [
        { title: 'Write or paste your prompt into the editor', text: 'Type directly in the large editor on the left, or paste an existing prompt you want to improve. The quality score and mini bar chart at the bottom update in real time as you type — watch individual dimension bars rise as you add a role, a format, or constraints to your prompt.' },
        { title: 'Read the Analyze tab for the full breakdown', text: 'Click the Analyze tab on the right panel to see the overall score (0–10) and individual scores for all 8 dimensions: Role, Task, Format, Context, Constraints, Examples, Audience, and Tone. The color-coded bars make it immediately obvious which dimensions are weak. The Issues Found section below lists any detected anti-patterns with specific, actionable fix recommendations.' },
        { title: 'Fix flagged issues one by one', text: 'Work through each issue in the Issues panel. Add a role ("You are a senior engineer with 10 years of Python experience"), specify an output format ("Format as a numbered list with severity labels"), add constraints ("Avoid style suggestions — focus only on bugs and security vulnerabilities"). Watch the score climb toward 7 or above. A score of 7+ is a reliable indicator that the prompt has enough structure to produce consistent, focused responses.' },
        { title: 'Load a template if you are starting from scratch', text: 'Click the Templates tab, select a category from the filter row (Coding, Writing, Analysis, Creative, Business, SEO, or Data), and click "Use Template →" on any card. The full template text loads into the editor immediately and the analyzer scores it — you can see exactly what structural elements make it effective before you replace the [placeholder] sections with your own content.' },
        { title: 'Optimize the prompt for your target AI model', text: 'Click the Optimize tab and select Claude, ChatGPT, or Gemini. Claude gets XML structural tags (<role>, <instructions>, <output_format>) that give it explicit scope boundaries. ChatGPT gets a persona statement at the top and numbered instructional steps. Gemini gets a "Think step by step" priming line and an explicit Output format declaration with headers. Click Copy to grab the model-specific version and paste it directly into the AI interface.' },
        { title: 'Save prompts you want to reuse', text: 'Click Save above the editor, optionally give the prompt a descriptive title (e.g. "Code Review — Python security focus"), and confirm. Saved prompts appear in the Library tab with their quality score displayed next to the title. They persist in your browser\'s localStorage across sessions — no account or login required. Treat the library as your personal prompt template collection.' },
        { title: 'Search and load from your library', text: 'Open the Library tab and type in the search box to filter by title or prompt content. Click Load to restore any saved prompt into the editor — the analyzer updates immediately so you can refine it further. Use Copy to grab a prompt from the library without switching to the editor. Use Delete to remove prompts you no longer need.' },
        { title: 'Share a prompt or bookmark it via URL', text: 'Click Share above the editor to copy a URL that encodes the current prompt as a Base64 string in the query parameter. Anyone who opens the link has the prompt pre-loaded in the tool with the analyzer ready — no account, no setup. Use this to share refined prompts with teammates in Slack or Notion, post working examples in team documentation, or save a high-scoring prompt as a browser bookmark you can return to.' },
      ],
    },
    {
      type: 'cards',
      heading: 'Common Use Cases',
      columns: 3,
      items: [
        { icon: '◎', title: 'Debug a prompt that keeps getting generic responses', desc: 'Paste the disappointing prompt into the analyzer. The dimension breakdown shows exactly what is missing — usually no role, no output format, and no constraints. Fix each issue the panel flags, watch the score climb, then use Optimize to generate a model-specific version before sending.' },
        { icon: '⚙', title: 'Write a prompt for a task you\'ve never done before', desc: 'Open Templates, pick the closest category, and load an expert template. Read how it\'s structured — role, task verb, numbered requirements, format spec, and [placeholders]. Replace each placeholder with your content, then check the Analyze tab to verify you\'ve maintained the quality.' },
        { icon: '△', title: 'A/B test the same prompt on Claude vs. ChatGPT', desc: 'Write and score your prompt to 7+. Go to Optimize, select Claude, copy the XML-structured version, paste into Claude. Switch to ChatGPT, copy the persona-prefixed version, paste into ChatGPT. Same intent, model-native format — removes format noise from your comparison.' },
        { icon: '◫', title: 'Build a personal library for your recurring tasks', desc: 'If you prompt AI tools daily for code review, email drafts, or data analysis, you\'re re-writing the same structure every time. Write each prompt once, score it to 7+, save it with a descriptive title. Load it next time, swap in the specific context, and send — seconds instead of minutes. Keep longer reference notes alongside them in the [browser notepad](https://fwdtools.com/notepad).' },
        { icon: '⊞', title: 'Teach a team to write better prompts', desc: 'Write an ideal prompt for a shared task, score it to 8+, and click Share. Paste the URL into Slack or a team wiki. Teammates open it with the analyzer active — they can see the score, read the dimension breakdown, and understand why the structure works. More useful than a written guide. For prompts that generate JSON, validate the output with the [JSON formatter](https://fwdtools.com/json-formatter).' },
        { icon: '✓', title: 'Pre-check a stakeholder-supplied prompt', desc: 'A client or manager hands you a prompt to run. Paste it into the analyzer first. A score below 5 with flagged issues means the output will need multiple clarification rounds — the Issues panel tells you exactly what to ask them to clarify before you spend tokens on a bad prompt.' },
      ],
    },
    {
      type: 'faq',
      heading: 'Frequently Asked Questions',
      items: faqSchema.mainEntity.map(q => ({ q: q.name, a: q.acceptedAnswer.text })),
    },
  ],
};

export default function AiPromptStudioPage() {
  return (
    <div className={styles.page}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />
      <div className={styles.toolSection}><AiPromptStudioTool /></div>
      <IndexOnly><AdSlot />
      <SeoSection {...SEO} /></IndexOnly>


    </div>
  );
}
