import styles from '../privacy-policy/styles.module.css';

export const metadata = {
  title: 'Terms & Conditions — webdevpuneet.com User Agreement | webdevpuneet.com',
  description: 'Terms and conditions for using webdevpuneet.com — free browser-based developer and freelancer tools. No account required. All tools run in your browser.',
  alternates: { canonical: 'https://webdevpuneet.com/terms/' },
  robots: { index: true, follow: true },
};

export default function Terms() {
  const year = new Date().getFullYear();
  return (
    <div className={styles.page}>
      <div className={styles.inner}>
        <h1 className={styles.title}>Terms &amp; Conditions</h1>
        <p className={styles.updated}>Last updated: July 2, 2026</p>

        <section className={styles.section}>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using webdevpuneet.com at <strong>webdevpuneet.com</strong> (the "Service"), you agree to be bound by these Terms &amp; Conditions ("Terms") and by our <a href="/privacy-policy/">Privacy Policy</a>, which is incorporated by reference. If you do not agree to these Terms, please discontinue use of the Service immediately. We may offer the Service in different languages; in the event of any conflict, the English version of these Terms controls.</p>
        </section>

        <section className={styles.section}>
          <h2>2. Description of Service</h2>
          <p>webdevpuneet.com provides a collection of free, browser-based utilities for developers and freelancers, including but not limited to code formatters, converters, calculators, generators, and productivity tools. All tools are designed to run <strong>entirely client-side</strong> — processing happens inside your own browser using JavaScript, and your input is not uploaded to or stored on our servers unless a specific tool explicitly states otherwise (for example, an optional cloud-sync feature that you must actively enable using your own third-party credentials).</p>
          <p>The Service is provided free of charge and is supported by advertising. We do not guarantee that any specific tool will remain available indefinitely, be free of interruption, or be added, changed, or removed at any time without notice.</p>
        </section>

        <section className={styles.section}>
          <h2>3. Eligibility & Fair Use</h2>
          <p>The Service is intended for general audiences and is not directed at children under 13. By using the Service you represent that you have the legal capacity to enter into these Terms. All tools are free to use for personal and commercial purposes, and you may use any output generated by a tool (code, formatted data, exported files, calculations, etc.) without restriction. You agree not to:</p>
          <ul>
            <li>Use the Service to create, distribute, or store malware, spam, or unlawful content</li>
            <li>Scrape, crawl, reverse-engineer, or use automated means to access the Service in a way that places unreasonable load on our infrastructure or disrupts service for other users</li>
            <li>Attempt to bypass, disable, or interfere with security-related features of the Service</li>
            <li>Misrepresent the source or authorship of content generated using the Service</li>
            <li>Use the Service in any way that violates applicable local, national, or international law</li>
          </ul>
          <p>We reserve the right to rate-limit, block, or restrict access for any user or IP address engaged in abusive, excessive, or automated use that degrades the Service for others.</p>
        </section>

        <section className={styles.section}>
          <h2>4. Advertising & Third-Party Content</h2>
          <p>The Service displays advertising served by <strong>Google AdSense</strong> and may display content from other third-party advertising networks. We do not control the specific content of individual ads and are not responsible for the products, services, or claims made in third-party advertisements. Your interactions with any advertiser are solely between you and that advertiser. See our <a href="/privacy-policy/">Privacy Policy</a> for details on advertising cookies and how to opt out of personalized advertising.</p>
        </section>

        <section className={styles.section}>
          <h2>5. No Warranty / Disclaimer</h2>
          <p>THE SERVICE IS PROVIDED <strong>"AS IS"</strong> AND <strong>"AS AVAILABLE"</strong> WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT. Because all tools run client-side and are provided for general convenience, we make no guarantee as to:</p>
          <ul>
            <li>The accuracy, completeness, or reliability of any calculation, conversion, or generated output</li>
            <li>Uninterrupted, timely, secure, or error-free operation of the Service</li>
            <li>That defects will be corrected, or that the Service is free of viruses or other harmful components</li>
          </ul>
          <p>Outputs from calculators, code generators, and similar tools are provided for informational and productivity purposes only and should not be relied upon as professional, legal, financial, tax, medical, or engineering advice. Always independently verify important results before relying on them.</p>
        </section>

        <section className={styles.section}>
          <h2>6. Limitation of Liability</h2>
          <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL FWD TOOLS, ITS OWNER, OR ITS CONTRIBUTORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, REVENUE, OR BUSINESS OPPORTUNITY, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Because the Service is provided free of charge, our total aggregate liability for any claim arising from these Terms or your use of the Service shall not exceed <strong>USD $50</strong> or the amount (if any) you paid us in the twelve months preceding the claim, whichever is greater. Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the above limitations may not apply to you.</p>
        </section>

        <section className={styles.section}>
          <h2>7. Indemnification</h2>
          <p>You agree to indemnify and hold harmless webdevpuneet.com and its owner from any claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising out of your use of the Service, your violation of these Terms, or your violation of any rights of a third party.</p>
        </section>

        <section className={styles.section}>
          <h2>8. Data & Privacy</h2>
          <p>We do not collect, store, or transmit content you enter into our tools — all processing happens locally in your browser. Certain tools may store data in your browser's localStorage or IndexedDB, or offer an optional sync to a third-party service using credentials you control. Please refer to our <a href="/privacy-policy/">Privacy Policy</a> for full details on cookies, analytics, advertising, and your privacy rights under GDPR and CCPA.</p>
        </section>

        <section className={styles.section}>
          <h2>9. Intellectual Property</h2>
          <p>The webdevpuneet.com name, logo, site design, and underlying source code are the intellectual property of the site owner and are protected by applicable copyright and trademark law. The tools are built for public use — you are free to use any output generated by the tools without restriction — but you may not copy, resell, sublicense, or redistribute the Service itself, its design, or its source code without prior written permission.</p>
        </section>

        <section className={styles.section}>
          <h2>10. Third-Party Links</h2>
          <p>The Service may contain links to external websites, including advertiser links and references to third-party tools or resources. We are not responsible for the content, accuracy, security, or privacy practices of any third-party site, and inclusion of a link does not imply endorsement.</p>
        </section>

        <section className={styles.section}>
          <h2>11. Modifications to the Service and Terms</h2>
          <p>We reserve the right to modify, suspend, or discontinue any tool or feature of the Service at any time, with or without notice, and without liability to you. We may also revise these Terms at any time; the "Last updated" date at the top of this page reflects the most recent revision. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms.</p>
        </section>

        <section className={styles.section}>
          <h2>12. Termination</h2>
          <p>We may restrict, suspend, or terminate your access to all or part of the Service at any time, without notice, if we believe you have violated these Terms or engaged in conduct that is harmful to the Service or other users. Because no account is required to use the Service, "termination" generally means blocking further access from the device, network, or credentials associated with the violation.</p>
        </section>

        <section className={styles.section}>
          <h2>13. Severability</h2>
          <p>If any provision of these Terms is found to be unenforceable or invalid under applicable law, that provision will be limited or eliminated to the minimum extent necessary so that the remaining Terms remain in full force and effect.</p>
        </section>

        <section className={styles.section}>
          <h2>14. Governing Law</h2>
          <p>These Terms are governed by and construed in accordance with the laws applicable to the site owner, without regard to conflict-of-law principles. Any dispute arising from these Terms or use of the Service shall be resolved in the courts having jurisdiction over the site owner, except where applicable consumer protection law requires otherwise.</p>
        </section>

        <section className={styles.section}>
          <h2>15. Entire Agreement</h2>
          <p>These Terms, together with the Privacy Policy, constitute the entire agreement between you and webdevpuneet.com regarding use of the Service and supersede any prior agreements or understandings, whether written or oral.</p>
        </section>

        <section className={styles.section}>
          <h2>16. Contact</h2>
          <p>For any questions regarding these Terms &amp; Conditions, please reach out via the <a href="/contact/">contact page</a>, or by email at <a href="mailto:puneet438@gmail.com">puneet438@gmail.com</a>.</p>
        </section>

        <p className={styles.footer}>© {year} webdevpuneet.com</p>
      </div>
    </div>
  );
}
